=== fxdevGer/Dependency-Injection/DependencyInjection/09_xsd/core/core.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
    xmlns="http://privatefunction.net/playground/di/xsd/core/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://privatefunction.net/playground/di/xsd/core/">
	
	<xs:element name="context">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="localization" type="localizationType" minOccurs="0" maxOccurs="1"/>
                <xs:element name="factory" type="factoryType" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="factoryType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="object" type="topLevelObjectType"/>
            <xs:any namespace="##other"/>
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="topLevelObjectType">
        <xs:complexContent>
            <xs:extension base="objectType">
                <xs:attributeGroup ref="rootObjectAttributes"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
     
    <xs:complexType name="objectType">
       <xs:sequence>
       		<xs:group ref="objectCreation" minOccurs="0" maxOccurs="1"/>
       		<xs:group ref="objectLoaderGroup" minOccurs="0" maxOccurs="unbounded"/>
       		<xs:group ref="objectMediaTask" minOccurs="0" maxOccurs="unbounded"/>
       		<xs:group ref="objectPropertyV3D" minOccurs="0" maxOccurs="unbounded"/>
       		<xs:group ref="objectProperty" minOccurs="0" maxOccurs="unbounded"/>
       		<xs:group ref="objectMethod" minOccurs="0" maxOccurs="unbounded"/>
            <xs:group ref="objectNamespace" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:attributeGroup name="rootObjectAttributes">
        <xs:attribute name="id" type="xs:token" use="required"/>
        <xs:attribute name="class" type="xs:token" use="optional"/>
        <xs:attribute name="ref" type="xs:token" use="optional"/>  
        <xs:attribute name="initMethod" type="xs:token" use="optional"/> 
        <xs:attribute name="lifetime" type="xs:token" use="optional"/>
        <xs:attribute name="childsInjection" type="xs:token" use="optional"/>
    </xs:attributeGroup>
    
     <xs:group name="objectCreation">
        <xs:choice>
            <xs:element name="constructor-args" type="arrayType"/>
        </xs:choice>
    </xs:group>
    
    <xs:group name="objectLoaderGroup">
    	<xs:choice>
    		<xs:element name="loaderGroup" type="loaderGroupType"/>
    	</xs:choice>
    </xs:group>
    
    <xs:group name="objectMediaTask">
        <xs:choice>
            <xs:element name="mediaTask" type="mediaTaskType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:group>
    
    <xs:group name="objectProperty">
        <xs:choice>
            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:group>
    
    <xs:group name="objectPropertyV3D">
        <xs:choice>
            <xs:element name="vector3D" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:group>
    
    <xs:group name="objectMethod">
        <xs:choice>
            <xs:element name="method" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:group>
    
    <xs:group name="objectNamespace">
        <xs:sequence>
            <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>
    
    <xs:complexType name="loaderGroupType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
        	<xs:element name="loaderTask" type="loaderTaskType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="loaderGroupAttributes"/>	
    </xs:complexType>
    
    <xs:complexType name="loaderTaskType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
        	<xs:element name="array" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="loaderTaskAttributes"/>	
    </xs:complexType>
    
     <xs:attributeGroup name="loaderGroupAttributes">
        <xs:attribute name="id" type="xs:token" use="required"/>
        <xs:attribute name="groupState" type="xs:token" use="optional"/>
        <xs:attribute name="groupLoad" type="xs:token" use="optional"/>
        <xs:attribute name="groupCache" type="xs:token" use="optional"/>
    </xs:attributeGroup>
	
    <xs:attributeGroup name="loaderTaskAttributes">
        <xs:attribute name="method" type="xs:token" use="optional"/>
    </xs:attributeGroup>
    
    <xs:complexType name="propertyType">
    	<xs:sequence minOccurs="0">
    		<xs:group ref="value" />
    	</xs:sequence>
    	<xs:attribute name="name" type="xs:token" use="required" />
    	<xs:attribute name="value" type="xs:token" use="optional" />
    	<xs:attribute name="boolean" type="xs:boolean" use="optional"/>
    	<xs:attribute name="id-ref" type="xs:token" use="optional" />
    	<xs:attribute name="value-ref" type="xs:token" use="optional" />
    	<xs:attribute name="arguments" type="xs:token" use="optional" />
    </xs:complexType>

    <xs:complexType name="localizationType">
        <xs:sequence>
            <xs:element name="localeManager" type="localeManagerType" minOccurs="0"/>
            <xs:element name="messageSource" type="messageSourceType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="localeManagerType">
        <xs:sequence>
            <xs:element name="defaultLocale" type="localeType" minOccurs="0"/>
            <xs:element name="locale" type="localeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence> 
        <xs:attribute name="type" type="xs:token" use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="localeType">
        <xs:attribute name="language" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:pattern value="[a-z]{2}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="country" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:pattern value="[a-z].+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>  
        <xs:attribute name="ignoreCountry" type="xs:boolean" use="optional"/>      
    </xs:complexType>
    
    <xs:complexType name="messageSourceType">
        <xs:sequence>
            <xs:element name="default-message-bundle" type="messageBundleType" minOccurs="0"/>
            <xs:element name="messageBundle" type="messageBundleType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
       	<xs:attributeGroup ref="loaderGroupAttributes"/>
        <xs:attribute name="type" type="xs:token" use="optional"/>
        <xs:attribute name="bundle-type" type="xs:token" use="optional"/>
    </xs:complexType>

    <xs:complexType name="messageBundleType">
        <xs:attribute name="id" type="xs:token" use="required"/>
        <xs:attribute name="basename" type="xs:token" use="required"/>
    </xs:complexType>

     <xs:complexType name="mediaTaskType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
        	<xs:element name="array" type="xs:token" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="mediaObjectAttributes"/>	
    </xs:complexType>
    
     <xs:attributeGroup name="mediaObjectAttributes">
        <xs:attribute name="method" type="xs:token" use="required"/>
    </xs:attributeGroup>
    
    <xs:complexType name="arrayType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:group ref="value"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:group name="value">
        <xs:choice>
            <xs:element name="boolean" type="booleanOrExpression"/>
            <xs:element name="number" type="numberOrExpression"/>
            <xs:element name="int" type="intOrExpression"/>
            <xs:element name="uint" type="uintOrExpression"/>
            <xs:element name="vector3D" type="expressionVector"/>
            <xs:element name="string" type="xs:string"/>
            <xs:element name="date" type="dateOrExpression"/>
            <xs:element name="id-ref" type="xs:token"/>
            <xs:element name="array" type="arrayType"/>
            <!-- 
            	<xs:element name="null" type="emptyType"/> 	
            	<xs:element name="class" type="xs:token"/> 
           		<xs:element name="static-property" type="staticPropertyType"/>
            	<xs:element name="object" type="objectType"/>
            	<xs:element name="object-ref" type="refType"/>
            	<xs:any namespace="##other"/>
             -->
        </xs:choice>
    </xs:group>
    
    <xs:complexType name="emptyType"/>
    
    <xs:simpleType name="expression">
        <xs:restriction base="xs:token">
            <xs:pattern value="\$\{.+\}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    
     <xs:simpleType name="expressionVector">
        <xs:restriction base="xs:token">
            <xs:pattern value="-?[0-9]{0,4},-?[0-9]{0,4},-?[0-9]{0,4}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="date">
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}( [0-9]{1,2}:[0-9]{2}:[0-9]{2})?"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="booleanOrExpression">
        <xs:union memberTypes="xs:boolean expression"/>
    </xs:simpleType>
    
    <xs:simpleType name="numberOrExpression">
        <xs:union memberTypes="xs:double hexValue expression"/>
    </xs:simpleType>
    
    <xs:simpleType name="intOrExpression">
        <xs:union memberTypes="xs:int hexValue expression"/>
    </xs:simpleType>
    
    <xs:simpleType name="uintOrExpression">
        <xs:union memberTypes="xs:nonNegativeInteger nonNegativeHexValue expression"/>
    </xs:simpleType>
    
    <xs:simpleType name="nonNegativeHexValue">
        <xs:restriction base="xs:token">
            <xs:pattern value="0[Xx][0-9a-fA-F]+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="hexValue">
        <xs:restriction base="xs:token">
            <xs:pattern value="-?0[Xx][0-9a-fA-F]+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="dateOrExpression">
        <xs:union memberTypes="date expression"/>
    </xs:simpleType>
    
    <!-- 
    
    <xs:complexType name="staticPropertyType">
        <xs:attribute name="type" type="xs:token" use="required"/>
        <xs:attribute name="property" type="xs:token" use="required"/>
    </xs:complexType>
    <xs:complexType name="refType">
        <xs:attribute name="id-ref" type="xs:token" use="optional"/>
        <xs:attribute name="type-ref" type="xs:token" use="optional"/>
        <xs:attribute name="required" type="xs:token" use="optional"/>
    </xs:complexType>
    
     -->
    
</xs:schema>

=== fxdevGer/Dependency-Injection/DependencyInjection/02_deploy/config/topics/context_localization.xml
<?xml version="1.0" encoding="utf-8"?>
<context xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://privatefunction.net/playground/di/xsd/core/"
	xsi:schemaLocation="http://privatefunction.net/playground/di/xsd/core/ http://privatefunction.net/playground/di/xsd/core/core.xsd ">
	
	<localization>
		<localeManager>
			<defaultLocale language="de" country="germany" ignoreCountry="true" />	<!-- sets the defaultLocale to de -->
			<locale language="en" country="great britain" ignoreCountry="true" />	<!-- you can define as many locale you need -->
			<locale language="fr" country="france" ignoreCountry="true" />
		</localeManager>
		 
		<messageSource id="messages" groupState="active" groupLoad="altogether" groupCache="on">	<!-- id:identifier for this object, groupState:active or suspend, groupLoad:sequential or altogether, groupCache:on or off-->
			<messageBundle id="navigation" basename="messages/navigation/navigation" />				<!-- define as many messageBundles you need for each locale -->
			<messageBundle id="description" basename="messages/description/description" />
			<messageBundle id="form" basename="messages/form/form" />
		</messageSource>
	</localization>
	
	<factory/>
	
</context>

=== fxdevGer/Dependency-Injection/DependencyInjection/02_deploy/config/topics/context_methods.xml
<?xml version="1.0" encoding="utf-8"?>
<context xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://privatefunction.net/playground/di/xsd/core/"
	xsi:schemaLocation="http://privatefunction.net/playground/di/xsd/core/ http://privatefunction.net/playground/di/xsd/core/core.xsd ">
	
	<factory>
		<object id="simpleReferenceById" class="cs.unit.test.examples.ExampleSimpleReferenceById"/> <!-- Simple Class without any Function need for injection via id-ref as property -->
		
		<!-- 
			name: defines the name of the Method which will be called
			value: defines the value that is passed through the Method
			id-ref: defines a Reference by Id
			value-ref: defines values from id-ref
		 -->
		
		<object id="exampleMethods" class="cs.unit.test.examples.ExampleMethods" childsInjection="afterLoading">
			<method name="simpleMethod"/>																	<!-- calls Method simpleMethod in ExampleMethods -->
			<method name="simpleMethodWithArguments" arguments="1,10"/>																	<!-- calls Method simpleMethod in ExampleMethods -->
			<method name="simpleMethodForIdRef" id-ref="simpleReferenceById"/>								<!-- calls Method simpleMethodForIdRef with argument simpleReferenceById -->
			<method name="simpleMethodForValueRef" id-ref="simpleReferenceById" value-ref="simpleValue"/>	<!-- calls Method simpleMethodForIdRef with argument simpleReferenceById.simpleValue -->
			<method name="multiMethodForValueRef" id-ref="simpleReferenceById" value-ref="simpleValue, object, array, vector"/>	 <!-- calls Method simpleMethodForIdRef with arguments -->
			<method id-ref="exampleMethods" value-ref="returnsimpleMethodForIdRef" name="scaleMethod" value=".3"/> 				 <!-- calls setter exampleMethods.returnsimpleMethodForIdRef.scaleMethod(value) -->
			<method name="testForArguments" id-ref="simpleReferenceById" value-ref="object" arguments="100, 200"/> 				 <!-- calls setter exampleMethods.testForArguments(value-ref, arguments) -->
			<method name="testForArguments2" id-ref="simpleReferenceById" arguments="100, 200"/> 				 <!-- calls setter exampleMethods.testForArguments(value-ref, arguments) -->
		</object>
	</factory>
</context>

=== fxdevGer/Dependency-Injection/DependencyInjection/02_deploy/config/topics/context_input.xml
<?xml version="1.0" encoding="utf-8"?>
<context xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://privatefunction.net/playground/di/xsd/core/"
	xsi:schemaLocation="http://privatefunction.net/playground/di/xsd/core/ http://privatefunction.net/playground/di/xsd/core/core.xsd ">
	
	<factory>
		
		<object id="autoFireKeyDelay" class="com.cs.utils.input.AutoFireKeyDelay">
			<method name="autoFireKeyDelay" arguments="ArrowUp,50"/>
		</object>
		
		<object id="inputControl" class="com.cs.utils.input.Input">
			<property name="dispatchMouse" value="true" />
			<property name="dispatchClick" value="true" />
			<property name="registerKeyEvent" value="Left"/>
			<property name="registerKeyEvent" value="Right"/>
			<property name="registerKeyEvent" value="Space"/>
			<property name="registerKeyEvent" value="ArrowLeft"/>
			<property name="registerKeyEvent" value="ArrowRight"/>
			<property name="registerKeyEvent" value="ArrowUp"/>
			<property name="registerKeyEvent" value="ArrowDown"/>
			<property name="mouseHide" boolean="false" />
			<property name="autoFireKeyDelay" id-ref="autoFireKeyDelay"/>
		</object>
		
	</factory>
</context>

=== fxdevGer/Dependency-Injection/DependencyInjection/02_deploy/config/topics/context_mediatask.xml
<?xml version="1.0" encoding="utf-8"?>
<context xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://privatefunction.net/playground/di/xsd/core/"
	xsi:schemaLocation="http://privatefunction.net/playground/di/xsd/core/ http://privatefunction.net/playground/di/xsd/core/core.xsd ">
	
	<factory>
		<object id="exampleMediaTask" class="cs.unit.test.examples.ExampleMediaTask">
			<mediaTask method="addPath">				<!-- method:Method name for injection of values at Object -->
				<array>media/mp4/boxplus.mp4</array>
				<array>media/mp4/boxplus.mp4</array>
				<array>media/mp4/boxplus.mp4</array>
				<array>media/mp4/boxplus.mp4</array>
			</mediaTask>
		</object>
	</factory>
</context>

=== fxdevGer/Dependency-Injection/DependencyInjection/02_deploy/config/topics/context_loadergroup.xml
<?xml version="1.0" encoding="utf-8"?>
<context xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://privatefunction.net/playground/di/xsd/core/"
	xsi:schemaLocation="http://privatefunction.net/playground/di/xsd/core/ http://privatefunction.net/playground/di/xsd/core/core.xsd ">
	
	<factory>
	
		<!--
			id:identifier for this object, 
			class: Class Name for creation, 
			lifetime:object will be killed 
			
			if groupState == suspend you can call
			
			Context.fileLoader.addEventListener(Event.COMPLETE, handleLoadingComplete);
			Context.fileLoader.loadByGroupName("exampleLoaderGroup");
			
		-->
	
		<object id="exampleLoaderGroup" class="cs.unit.test.examples.ExampleLoaderGroup" lifetime="expire">		
			<!-- <loaderGroup id="exampleLoaderGroup" groupState="active" groupLoad="sequential" groupCache="on">	id:identifier for this object, groupState:active or suspend, groupLoad:sequential or altogether, groupCache:on or off
				<loaderTask method="addImage">																	method:Method name for injection of loaded Content at Object
					<array>media/images/0.jpg</array>
					<array>media/images/1.jpg</array>
					<array>media/images/2.jpg</array>
					<array>media/images/3.jpg</array>
					<array>media/images/4.jpg</array>
					<array>media/images/5.jpg</array>
					<array>media/images/cubeTexture.png</array>
					<array>media/images/texture_008.jpg</array>
				</loaderTask>
			</loaderGroup> -->
			<!-- <loaderGroup id="exampleLoaderGroup" groupState="active" groupLoad="sequential" groupCache="on">
				<loaderTask method="addShader">
					<array>media/shader/pixelate.pbj</array>
					<array>media/shader/reflectioneffect.pbj</array>
				</loaderTask>
			</loaderGroup> -->
			<!-- <loaderGroup id="exampleLoaderGroup" groupState="active" groupLoad="sequential" groupCache="on">
				<loaderTask method="addObjModel">
					<array>media/models/car.md5mesh</array>
				</loaderTask>
			</loaderGroup> -->
			<loaderGroup id="exampleLoaderGroup" groupState="active" groupLoad="sequential" groupCache="on">
				<loaderTask method="add3dsModel">
					<array>media/models/f360.3ds</array>
				</loaderTask>
			</loaderGroup>
			<loaderGroup id="exampleLoaderGroup" groupState="active" groupLoad="sequential" groupCache="on">
				<loaderTask method="addAWDModel">
					<array>media/models/konservendose.awd</array>
				</loaderTask>
			</loaderGroup>
		</object>
	</factory>

</context>

=== fxdevGer/Dependency-Injection/DependencyInjection/02_deploy/config/topics/context_constructor_args.xml
<?xml version="1.0" encoding="utf-8"?>
<context xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://privatefunction.net/playground/di/xsd/core/"
	xsi:schemaLocation="http://privatefunction.net/playground/di/xsd/core/ http://privatefunction.net/playground/di/xsd/core/core.xsd ">

	<factory>
	
		<!-- 
			Simple Class without any Function need for injection via id-ref at constructor-args 
		-->
		<object id="simpleReferenceById" class="cs.unit.test.examples.ExampleSimpleReferenceById"/> 
		
		<!-- 
			Class that will be created and injected with constructor - args 
			Important only 8 values are allowed
		-->
		
		<object id="constructor-argsExample" class="cs.unit.test.examples.ExampleConstructorArgs">	
			<constructor-args>													
				<boolean>false</boolean>															<!-- Simple Boolean -->
				<number>300</number>																<!-- Simple Number -->
				<int>-987654321</int>																<!-- Simple int -->
				<uint>123456789</uint>																<!-- Simple unit -->
				<string>Hallo ich bin ein Constructor String</string>								<!-- Simple String -->
				
				<array>																				<!-- Complex Type Array -->
					<boolean>false</boolean>
					<number>300</number>
					<int>-987654321</int>
					<uint>123456789</uint>
					<string>Hallo ich bin ein Constructor String</string>
				</array>
				
				<date>2011-7-26 12:00:00</date>														<!-- Simple Date -->
				<!-- <id-ref>simpleReferenceById.vector</id-ref> -->								<!-- Simple Reference, dot Operator Hack :D-->
				<vector3D>0,100,200</vector3D>
			</constructor-args>
		</object>
	</factory>
</context>

=== fxdevGer/Dependency-Injection/DependencyInjection/02_deploy/config/context_dev.xml
<?xml version="1.0" encoding="utf-8"?>
<context xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://privatefunction.net/playground/di/xsd/core/" xmlns:mvc="http://privatefunction.net/playground/di/xsd/mvc/"
	xsi:schemaLocation="http://privatefunction.net/playground/di/xsd/core/ http://privatefunction.net/playground/di/xsd/core/core.xsd http://privatefunction.net/playground/di/xsd/mvc/ http://privatefunction.net/playground/di/xsd/mvc/mvc.xsd ">
	
	<localization>
		<localeManager>
			<defaultLocale language="de" country="germany" ignoreCountry="true" />
			<locale language="en" country="great britain" ignoreCountry="true" />
			<locale language="fr" country="france" ignoreCountry="true" />
		</localeManager>
		 
		<messageSource id="messages" groupState="active" groupLoad="altogether" groupCache="on">
			<messageBundle id="navigation" basename="messages/navigation/navigation" />
			<messageBundle id="description" basename="messages/description/description" />
			<messageBundle id="form" basename="messages/form/form" />
		</messageSource>
	</localization>
	<factory>
		<object id="libs">
			<loaderGroup id="libs" groupState="active" groupLoad="altogether" groupCache="on">
				<loaderTask>
					<array>media/swf/gfx.swf</array>
					<array>css/styles.css</array>
				</loaderTask>
			</loaderGroup>
		</object>
	
		<object id="galleryScreen" class="cs.unit.test.screens.types.GalleryScreen">
			<mediaTask method="addContexts">
				<array>config/context_gallery.xml</array>
			</mediaTask>
			<property name="modelString" value="galleryModel" />
			<property name="id" value="galleryScreen" />
		</object>
		
		<object id="videoModel" class="cs.unit.test.screens.models.VideoModel">
			<mediaTask method="addVideoPath">
				<array>media/mp4/boxplus.mp4</array>
				<array>media/mp4/boxplus.mp4</array>
				<array>media/mp4/boxplus.mp4</array>
				<array>media/mp4/boxplus.mp4</array>
			</mediaTask>
		</object>
		
		<object id="videoScreen" class="cs.unit.test.screens.types.VideoScreen" ref="videoModel" initMethod="initVideoPlayer">
			<property name="id" value="videoScreen" />
		</object>
		
		<object id="formScreen" class="cs.unit.test.screens.types.FormScreen" initMethod="initForm">
			<constructor-args>
				<string>Formular</string>				
				<string>http://www.google.de/</string>
			</constructor-args>
			<mediaTask method="addContexts">
				<array>context/context_form.xml</array>
			</mediaTask>
			<property name="id" value="formScreen" />
		</object>
		
		<object id="mp3Model" class="cs.unit.test.screens.models.MP3Model">
			<loaderGroup id="mp3Model" groupState="active" groupLoad="altogether" groupCache="on">
				<loaderTask method="addMusic">
					<array>media/mp3/jazz.mp3</array>
					<array>media/mp3/sound1.mp3</array>
				</loaderTask>
			</loaderGroup>
			<mediaTask method="addMP3Path">
				<array>media/mp3/sound1.mp3</array>
				<array>media/mp3/sound2.mp3</array>
				<array>media/mp3/sound3.mp3</array>
			</mediaTask>
		</object>
		
		<object id="mp3Screen" class="cs.unit.test.screens.types.MP3Screen" ref="mp3Model" initMethod="initSoundPlayer">
			<constructor-args>
				<string>MP3BG</string>
			</constructor-args>
			<property name="id" value="mp3Screen" />
		</object>
		
		<object id="suspendModel" class="cs.unit.test.screens.models.SuspendModel">
			<loaderGroup id="suspendModel" groupState="suspend" groupLoad="altogether" groupCache="off">
				<loaderTask method="addImage">
					<array>media/images/0.jpg</array>
					<array>media/images/1.jpg</array>
					<array>media/images/2.jpg</array>
					<array>media/images/3.jpg</array>
					<array>media/images/4.jpg</array>
					<array>media/images/5.jpg</array>
				</loaderTask>
			</loaderGroup>
		</object>
		
		<object id="suspendScreen" class="cs.unit.test.screens.types.SuspendScreen" ref="suspendModel">
			<property name="id" value="suspendScreen" />
		</object>
		
		<object id="language" class="cs.unit.test.screens.types.Language" initMethod="initLanguage">
			<constructor-args>
				<string>Language</string>
			</constructor-args>
		</object>
		
		<object id="screenModel" class="cs.unit.test.screens.models.ScreenModel">
			<property name="registerScreen" id-ref="videoScreen" /> 
			<property name="registerScreen" id-ref="formScreen" />
			<property name="registerScreen" id-ref="mp3Screen" /> 
			<property name="registerScreen" id-ref="galleryScreen" />
			<property name="registerScreen" id-ref="suspendScreen" /> 
		</object>
		
		<object id="navigation" class="cs.unit.test.screens.navigation.Navigation" ref="screenModel" initMethod="initNavigation">
		 	<constructor-args>
				<int>5</int>
			</constructor-args>
			<mvc:action event-name="PERFORM_LANGUAGE_CHANGE" event-class="cs.unit.test.screens.event.ScreenEvent" method="onChangeLanguage" />
		</object>
		
		<object id="screenController" class="cs.unit.test.screens.ScreenController" ref="screenModel">
			<mvc:action event-name="REQUEST_CHANGE" event-class="cs.unit.test.screens.event.ScreenEvent" method="onChangeScreenRequest" />
			<mvc:action event-name="REQUEST_LANGUAGE_CHANGE" event-class="cs.unit.test.screens.event.ScreenEvent" method="onChangeLanguageRequest" />
		</object>

		<object id="screenView" class="cs.unit.test.screens.ScreenView" ref="screenModel"> <!--  -->
			<mvc:action event-name="PERFORM_CHANGE" event-class="cs.unit.test.screens.event.ScreenEvent" method="onChangeScreen" />
			<mvc:action event-name="PERFORM_LANGUAGE_CHANGE" event-class="cs.unit.test.screens.event.ScreenEvent" method="onChangeLanguage" />
		</object>

	</factory>
</context>
